title: Just the Docs
description: A Jekyll theme for documentation
baseurl: ''
url: ''
permalink: pretty
exclude:
  - node_modules/
  - '*.gemspec'
  - '*.gem'
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
  - docs/tests/
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: '/[\s/]+/'
  rel_url: true
  button: false
heading_anchors: true
aux_links:
  Just the Docs on GitHub:
    - //github.com/pmarsceill/just-the-docs
aux_links_new_tab: false
nav_sort: case_sensitive
back_to_top: true
back_to_top_text: Back to top
footer_content: >-
  Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a
  href="https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt">MIT
  license.</a>
last_edit_timestamp: true
last_edit_time_format: '%b %e %Y at %I:%M %p'
gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub
gh_edit_repository: 'https://github.com/pmarsceill/just-the-docs'
gh_edit_branch: master
gh_edit_view_mode: tree
color_scheme: nil
ga_tracking: UA-2709176-10
ga_tracking_anonymize_ip: true
plugins:
  - jekyll-seo-tag
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
